addons:
  sauce_connect:
    username: "uw-it-aca-myuw"
    access_key:
      secure: "d6TOiITCC+g+bTEMYUiW9ywYnY9GyvRP5admJcvlaJLg7Lqcj5nkuwKQ9MGmSpSceCL9mjPVjn5/D6XcpehmJxC1YfpCu9N2hijdDiyCtmd/tBdQhdExNa+zzaXLg5uGllGc7mA+RFR8gojmQE6VtzI2WIdLYO/eWQfWhj35O/Y="
language: python
python:
  - "2.7"
  - "2.6"
install: pip install -r requirements.txt
before_script:
  - pip install coverage
  - pip install python-coveralls
  - pip install pep8
  - pip install sauceclient
  - pip install selenium
  - npm install jshint
  - cp travis-ci/manage.py manage.py
  - python manage.py syncdb --noinput
script:
  - pep8 myuw_mobile/ --exclude=migrations,myuw_mobile/test,myuw_mobile/management
  - jshint myuw_mobile/static/js/  --verbose
  - REMOTE_USER=javerage RUN_SELENIUM=True coverage run --source=myuw_mobile/ manage.py test myuw_mobile
after_script:
  - coveralls
notifications:
  webhooks:
      urls:
        - https://yarn.cac.washington.edu/rest/botalyst/v1/travis-ci

