addons:
  sauce_connect:
    username: "uw-it-aca-myuw"
    access_key:
      secure: "c83+uoOlx/1eiYzPpdBqaUl8NL/R4zZhRK8bBNAwdDHVbrGqBjM2fRZ9RBexj89mX1DSvXCMMTmzexPjb+m1KTPVWI9VBXpZaGQdmmubZqoRPpHXU518U5oxoUl/EQZSM7js5qHCFpeVCCgDMjBw9bcoS33OAl4E2VvsYB106cQ="
language: python
python:
  - "2.7"
  - "2.6"
install: pip install -r requirements.txt
before_script:
  - pip install coverage
  - pip install python-coveralls
  - pip install pep8
  - pip install sauceclient
  - pip install selenium
  - npm install jshint
  - cp travis-ci/manage.py manage.py
  - python manage.py syncdb --noinput
script:
  - pep8 myuw_mobile/ --exclude=migrations,myuw_mobile/test,myuw_mobile/management
  - jshint myuw_mobile/static/js/  --verbose
  - REMOTE_USER=javerage RUN_SELENIUM=True coverage run --source=myuw_mobile/ manage.py test myuw_mobile
after_script:
  - coveralls
notifications:
  webhooks:
      urls:
        - https://yarn.cac.washington.edu/rest/botalyst/v1/travis-ci

